/*
 * AUTO-GENERATED FILE. DO NOT MODIFY. This class was automatically generated by the aapt tool from
 * the resource data it found. It should not be modified by hand.
 */

package org.metawidget.example.android.addressbook;

public final class R {

	public static final class attr {
		// Empty block
	}

	public static final class drawable {

		public static final int	icon	= 0x7f020000;
	}

	public static final class id {

		public static final int	communications	= 0x7f070001;

		public static final int	contacts		= 0x7f070002;

		public static final int	metawidget		= 0x7f070000;
	}

	public static final class layout {

		public static final int	contact	= 0x7f030000;

		public static final int	main	= 0x7f030001;
	}

	public static final class raw {

		public static final int	metawidget			= 0x7f040000;

		public static final int	metawidget_metadata	= 0x7f040001;
	}

	public static final class string {

		public static final int	add							= 0x7f050007;

		public static final int	addBusiness					= 0x7f050004;

		public static final int	addCommunication			= 0x7f05000f;

		public static final int	addError					= 0x7f050008;

		public static final int	addPersonal					= 0x7f050002;

		/**
		 * Strings that are manually localized
		 */
		public static final int	app_name					= 0x7f050000;

		public static final int	businessContact				= 0x7f050005;

		public static final int	cancel						= 0x7f05000e;

		public static final int	city						= 0x7f050022;

		public static final int	company						= 0x7f05001d;

		public static final int	confirmDeleteCommunication	= 0x7f050012;

		public static final int	confirmDeleteContact		= 0x7f050017;

		public static final int	contactDetails				= 0x7f05001f;

		public static final int	contacts					= 0x7f050006;

		public static final int	dateError					= 0x7f05000c;

		public static final int	dateOfBirth					= 0x7f05001c;

		public static final int	delete						= 0x7f05000d;

		public static final int	deleteCommunication			= 0x7f050011;

		public static final int	deleteContact				= 0x7f050016;

		public static final int	edit						= 0x7f050009;

		public static final int	editCommunication			= 0x7f050010;

		/**
		 * Strings that are localized by Metawidget
		 */
		public static final int	firstname					= 0x7f050018;

		public static final int	gender						= 0x7f05001e;

		public static final int	no							= 0x7f050015;

		public static final int	notes						= 0x7f050026;

		public static final int	numberOfStaff				= 0x7f050025;

		public static final int	ok							= 0x7f050013;

		public static final int	other						= 0x7f050020;

		public static final int	personalContact				= 0x7f050003;

		public static final int	postcode					= 0x7f050024;

		public static final int	save						= 0x7f05000a;

		public static final int	saveError					= 0x7f05000b;

		public static final int	search						= 0x7f050001;

		public static final int	state						= 0x7f050023;

		public static final int	street						= 0x7f050021;

		public static final int	surname						= 0x7f050019;

		public static final int	title						= 0x7f05001b;

		public static final int	type						= 0x7f05001a;

		public static final int	yes							= 0x7f050014;
	}

	public static final class style {

		public static final int	section	= 0x7f060000;
	}
}
