<?php $title = 'Screenshots'; $useThumbailViewer = true; require_once 'include/page-start.php'; ?>

	<?php require_once 'include/body-start.php'; ?>

		<h2>Screenshots</h2>
		
		<p>
			This page showcases screenshots from applications using Metawidget. Note
			the look and feel, layout and platform are all application-specific, not
			dictated by Metawidget.
		</p>

		<table id="table-screenshots">
			<tbody>
				<tr>
					<td align="center" valign="top">
						<a href="media/screenshots/desktop-addressbook.jpg" rel="lightbox">
							<img src="media/screenshots/desktop-addressbook-thumbnail.jpg" alt=""/>
						</a>
						<strong>Several Metawidgets embedded in a Swing application</strong><br/>
						The fields and buttons are all generated by Metawidget. The foreground and background images, and the JDialog, are managed by Swing
					</td>
					<td align="center" valign="top">
						<a href="media/screenshots/web-onecentral.jpg" rel="lightbox">
							<img src="media/screenshots/web-onecentral-thumbnail.jpg" alt=""/>
						</a>
						<strong>A Metawidget embedded in a JSF application</strong><br/>
						All fields are generated by Metawidget, including the use of third-party components for the date pickers. The rest of the page is managed by JSF
					</td>
				</tr>
				<tr>
					<td align="center" valign="top">
						<a href="media/screenshots/web-seam-booking.jpg" rel="lightbox">
							<img src="media/screenshots/web-seam-booking-thumbnail.jpg" alt=""/>
						</a>
						<strong>Two Metawidgets retrofitted into the Seam Hotel Booking application</strong><br/>
						The hotel information is a read-only Metawidget. The check-in information is a writable Metawidget. The rest of the page is managed by JSF and Seam
					</td>
					<td align="center" valign="top">
						<a href="media/screenshots/web-seam-dvd.jpg" rel="lightbox">
							<img src="media/screenshots/web-seam-dvd-thumbnail.jpg" alt=""/>
						</a>
						<strong>A Metawidget retrofitted into the Seam DVD Store application</strong><br/>
						The account registration fields are generated by Metawidget. The Prev and Next buttons are also generated by Metawidget, based on a jBPM pageflow
						file. The rest of the page is managed by JSF and Seam
					</td>
				</tr>
				<tr>
					<td align="center" valign="top">
						<a href="media/screenshots/web-addressbook.jpg" rel="lightbox">
							<img src="media/screenshots/web-addressbook-thumbnail.jpg" alt=""/>
						</a>
						<strong>Several Metawidgets embedded in a GWT application</strong><br/>
						The fields and buttons are all generated by Metawidget. The foreground and background images, and the pop-up, are managed by GWT and JavaScript
					</td>
					<td align="center" valign="top">
						<a href="media/screenshots/mobile-addressbook.jpg" rel="lightbox">
							<img src="media/screenshots/mobile-addressbook-thumbnail.jpg" alt=""/>
						</a>
						<strong>A Metawidget embedded in a mobile-phone application</strong><br/>
						The fields are all generated by Metawidget. The rest of the screen is managed by Android
					</td>
				</tr>
				<tr>
					<td align="center" valign="top">
						<a href="media/screenshots/desktop-animalraces.jpg" rel="lightbox">
							<img src="media/screenshots/desktop-animalraces-thumbnail.jpg" alt=""/>
						</a>
						<strong>Several Metawidgets embedded in a Swing application</strong><br/>
						The fields and buttons are all generated by Metawidget. The rest of the UI is managed by Swing
					</td>
					<td align="center" valign="top">
						<a href="media/screenshots/web-benefitcentral.jpg" rel="lightbox">
							<img src="media/screenshots/web-benefitcentral-thumbnail.jpg" alt=""/>
						</a>
						<strong>A Metawidget embedded in a JSF application</strong><br/>
						All fields are generated by Metawidget, including the use of third-party components for the date pickers and spinner control. The rest of the page is managed by JSF
					</td>
				</tr>
				<tr>
					<td align="center" valign="top">
						<a href="media/screenshots/desktop-energy.jpg" rel="lightbox">
							<img src="media/screenshots/desktop-energy-thumbnail.jpg" alt=""/>
						</a>
						<strong>A Metawidget embedded in a Swing application</strong><br/>
						The fields are generated by Metawidget. The surrounding JFrame, and the rest of the UI, is managed by Swing
					</td>
				</tr>
			</tbody>
		</table>
		
		<div style="height: 250px"></div>
				
	<?php require_once 'include/body-end.php'; ?>		

<?php require_once 'include/page-end.php'; ?>
